FROM ghcr.io/astral-sh/uv:0.12.3 AS uv

FROM python:3.13-alpine AS builder

COPY --from=uv /uv /usr/local/bin/uv

ENV UV_COMPILE_BYTECODE=1 UV_LINK_MODE=copy

WORKDIR /app

RUN --mount=type=cache,target=/root/.cache/uv \
    --mount=type=bind,source=uv.lock,target=uv.lock \
    --mount=type=bind,source=pyproject.toml,target=pyproject.toml \
    uv sync --python /usr/local/bin/python --frozen --no-build --only-group migration --no-install-workspace

FROM python:3.13-alpine

LABEL org.opencontainers.image.title="FastAPI Template Migration"
LABEL org.opencontainers.image.description="Alembic migration image for FastAPI template"
LABEL org.opencontainers.image.vendor="Subhransu-De"
LABEL org.opencontainers.image.source="https://github.com/Subhransu-De/fastapi-template"
LABEL org.opencontainers.image.base.name="python:3.13-alpine"

WORKDIR /app

RUN python -m pip uninstall --yes pip && \
    addgroup -S app && \
    adduser -S -G app -h /app -s /sbin/nologin app

COPY --from=builder /app/.venv /app/.venv

COPY alembic.ini /app/
COPY alembic /app/alembic

ENV PATH="/app/.venv/bin:$PATH"
ENV PYTHONUNBUFFERED=1

USER app

CMD ["alembic", "-c", "alembic.ini", "upgrade", "head"]
