ARG APP_IMAGE=fastapi-template:local
FROM ${APP_IMAGE}

COPY --from=public.ecr.aws/awsguru/aws-lambda-adapter:1.0.1@sha256:1e5ab4d9242167500ed8a7bed8a79b448228aaa51cf382fb51fe4bf8a5f9a811 /lambda-adapter /opt/extensions/lambda-adapter

ENV APP_HOST="0.0.0.0" \
    PORT="8080" \
    AWS_LWA_PORT="8080" \
    AWS_LWA_READINESS_CHECK_PATH="/health" \
    AWS_LWA_READINESS_CHECK_HEALTHY_STATUS="200" \
    AWS_LWA_INVOKE_MODE="buffered" \
    AWS_LWA_ASYNC_INIT="true" \
    PYTHONDONTWRITEBYTECODE="1"

EXPOSE 8080
