"""Create Entities table

Revision ID: 97f7686bdccd
Revises:
Create Date: 2026-01-24 20:12:27.427802+00:00

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "97f7686bdccd"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table("entities",
    sa.Column("name", sa.String(length=255), nullable=False),
    sa.Column("description", sa.Text(), nullable=True),
    sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
    sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
    sa.Column("id", sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint("id", name=op.f("pk_entities"))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("entities")
    # ### end Alembic commands ###
