from collections.abc import Iterator

import pytest
from asgi_lifespan import LifespanManager
from sqlalchemy import Connection, create_engine, delete, func, select, text
from sqlalchemy.exc import OperationalError
from sqlalchemy.ext.asyncio import AsyncEngine

from app.auth import OIDCOpenAPIFastAPI
from app.model import Entity
from seed import seed
from seed.fixtures import FIXTURES

pytestmark = pytest.mark.integration

IDENTITY_TABLE = (
    "CREATE TABLE {name} ("
    "id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name text)"
)


@pytest.fixture
def connection(test_postgres_url: str) -> Iterator[Connection]:
    engine = create_engine(test_postgres_url)
    try:
        with engine.connect() as connection:
            yield connection
            connection.rollback()
    finally:
        engine.dispose()


def _entity_rows(connection: Connection) -> list[tuple[object, ...]]:
    statement = select(Entity.__table__).order_by(Entity.id)
    return [tuple(row) for row in connection.execute(statement)]


def test_seeding_twice_changes_nothing(connection: Connection) -> None:
    connection.execute(delete(Entity))

    first = seed(connection, FIXTURES)
    rows_after_first = _entity_rows(connection)
    second = seed(connection, FIXTURES)

    assert first == {"entities": len(FIXTURES["entities"])}
    assert second == {"entities": 0}
    assert _entity_rows(connection) == rows_after_first


def test_next_insert_after_explicit_ids_gets_a_new_id(connection: Connection) -> None:
    connection.execute(text(IDENTITY_TABLE.format(name="seed_probe")))

    seed(connection, {"seed_probe": [{"id": 1, "name": "a"}, {"id": 7, "name": "b"}]})
    seed(connection, {"seed_probe": [{"id": 1, "name": "a"}, {"id": 7, "name": "b"}]})
    new_id = connection.scalar(
        text("INSERT INTO seed_probe (name) VALUES ('c') RETURNING id")
    )

    assert new_id == 8


def test_rows_without_a_primary_key_are_rejected(connection: Connection) -> None:
    connection.execute(text(IDENTITY_TABLE.format(name="seed_probe")))

    with pytest.raises(ValueError, match=r"must set the primary key \['id'\]"):
        seed(connection, {"seed_probe": [{"name": "a"}]})


def test_rows_with_different_columns_keep_their_own_values(
    connection: Connection,
) -> None:
    connection.execute(
        text(
            "CREATE TABLE seed_probe ("
            "id integer PRIMARY KEY, name text, note text DEFAULT 'none')"
        )
    )

    seed(
        connection,
        {
            "seed_probe": [
                {"id": 1, "name": "a"},
                {"id": 2, "name": "b", "note": "set"},
            ]
        },
    )
    notes = connection.execute(
        text("SELECT name, note FROM seed_probe ORDER BY id")
    ).all()

    assert [tuple(row) for row in notes] == [("a", "none"), ("b", "set")]


def test_rows_are_inserted_in_fixture_order(connection: Connection) -> None:
    connection.execute(
        text(
            "CREATE TABLE seed_probe ("
            "id integer PRIMARY KEY, parent integer REFERENCES seed_probe (id), "
            "note text)"
        )
    )

    inserted = seed(
        connection,
        {
            "seed_probe": [
                {"id": 1, "parent": None},
                {"id": 2, "parent": 1, "note": "x"},
                {"id": 3, "parent": 2},
            ]
        },
    )

    assert inserted == {"seed_probe": 3}


def test_rolled_back_seed_leaves_the_sequence_alone(test_postgres_url: str) -> None:
    engine = create_engine(test_postgres_url)
    try:
        with engine.begin() as setup:
            setup.execute(text(IDENTITY_TABLE.format(name="seed_rollback_probe")))
        with engine.connect() as seeding:
            seed(seeding, {"seed_rollback_probe": [{"id": 500, "name": "seeded"}]})
            seeding.rollback()
        with engine.begin() as writer:
            new_id = writer.scalar(
                text(
                    "INSERT INTO seed_rollback_probe (name) VALUES ('writer') "
                    "RETURNING id"
                )
            )
    finally:
        with engine.begin() as cleanup:
            cleanup.execute(text("DROP TABLE IF EXISTS seed_rollback_probe"))
        engine.dispose()

    assert new_id == 1


def test_concurrent_insert_waits_until_seeding_commits(test_postgres_url: str) -> None:
    engine = create_engine(test_postgres_url)
    insert_row = text("INSERT INTO seed_lock_probe (id, name) VALUES (6, 'writer')")
    try:
        with engine.begin() as setup:
            setup.execute(
                text("CREATE TABLE seed_lock_probe (id integer PRIMARY KEY, name text)")
            )
        with engine.connect() as seeding, engine.connect() as writer:
            seed(seeding, {"seed_lock_probe": [{"id": 5, "name": "seeded"}]})
            writer.execute(text("SET lock_timeout = '200ms'"))
            readable = writer.scalar(text("SELECT count(*) FROM seed_lock_probe"))
            with pytest.raises(OperationalError, match="lock timeout"):
                writer.execute(insert_row)
            writer.rollback()
            seeding.commit()
            writer.execute(insert_row)
            writer.commit()
            rows = writer.scalar(text("SELECT count(*) FROM seed_lock_probe"))
    finally:
        with engine.begin() as cleanup:
            cleanup.execute(text("DROP TABLE IF EXISTS seed_lock_probe"))
        engine.dispose()

    assert readable == 0
    assert rows == 2


async def test_application_startup_does_not_seed(
    integration_app: tuple[OIDCOpenAPIFastAPI, LifespanManager],
    integration_engine: AsyncEngine,
) -> None:
    async with integration_engine.connect() as connection:
        count = await connection.scalar(select(func.count()).select_from(Entity))

    assert count == 0
