from collections.abc import Iterator

import pytest
from asgi_lifespan import LifespanManager
from sqlalchemy import Connection, create_engine, delete, func, select, text
from sqlalchemy.exc import OperationalError
from sqlalchemy.ext.asyncio import AsyncEngine

from app.auth import OIDCOpenAPIFastAPI
from app.model import Entity
from seed import seed
from seed.fixtures import FIXTURES

pytestmark = pytest.mark.integration


@pytest.fixture
def connection(test_postgres_url: str) -> Iterator[Connection]:
    engine = create_engine(test_postgres_url)
    try:
        with engine.connect() as connection:
            yield connection
            connection.rollback()
    finally:
        engine.dispose()


def _entity_rows(connection: Connection) -> list[tuple[object, ...]]:
    statement = select(Entity.__table__).order_by(Entity.id)
    return [tuple(row) for row in connection.execute(statement)]


def test_seeding_twice_changes_nothing(connection: Connection) -> None:
    connection.execute(delete(Entity))

    first = seed(connection, FIXTURES)
    rows_after_first = _entity_rows(connection)
    second = seed(connection, FIXTURES)

    assert first == {"entities": len(FIXTURES["entities"])}
    assert second == {"entities": 0}
    assert _entity_rows(connection) == rows_after_first


@pytest.mark.parametrize("generation", ["ALWAYS", "BY DEFAULT"])
def test_next_insert_after_explicit_ids_gets_a_new_id(
    connection: Connection, generation: str
) -> None:
    connection.execute(
        text(
            "CREATE TABLE seed_probe ("
            f"id integer GENERATED {generation} AS IDENTITY PRIMARY KEY, name text)"
        )
    )

    seed(connection, {"seed_probe": [{"id": 1, "name": "a"}, {"id": 7, "name": "b"}]})
    new_id = connection.scalar(
        text("INSERT INTO seed_probe (name) VALUES ('c') RETURNING id")
    )
    generation_after_seed = connection.scalar(
        text(
            "SELECT identity_generation FROM information_schema.columns "
            "WHERE table_name = 'seed_probe' AND column_name = 'id'"
        )
    )

    assert new_id == 8
    assert generation_after_seed == generation


def test_sequence_never_moves_backwards(connection: Connection) -> None:
    connection.execute(
        text(
            "CREATE TABLE seed_probe ("
            "id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name text)"
        )
    )
    connection.execute(
        text("INSERT INTO seed_probe (name) SELECT 'x' FROM generate_series(1, 20)")
    )
    connection.execute(text("DELETE FROM seed_probe WHERE id > 2"))

    seed(connection, {"seed_probe": [{"id": 3, "name": "seeded"}]})
    new_id = connection.scalar(
        text("INSERT INTO seed_probe (name) VALUES ('c') RETURNING id")
    )

    assert new_id == 21


def test_concurrent_insert_waits_until_seeding_commits(test_postgres_url: str) -> None:
    engine = create_engine(test_postgres_url)
    try:
        with engine.begin() as setup:
            setup.execute(
                text(
                    "CREATE TABLE seed_lock_probe ("
                    "id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "
                    "name text)"
                )
            )
        with engine.connect() as seeding, engine.connect() as writer:
            seed(seeding, {"seed_lock_probe": [{"id": 5, "name": "seeded"}]})
            writer.execute(text("SET lock_timeout = '200ms'"))
            with pytest.raises(OperationalError, match="lock timeout"):
                writer.execute(
                    text("INSERT INTO seed_lock_probe (name) VALUES ('writer')")
                )
            writer.rollback()
            seeding.commit()
            new_id = writer.scalar(
                text(
                    "INSERT INTO seed_lock_probe (name) VALUES ('writer') RETURNING id"
                )
            )
            writer.commit()
    finally:
        with engine.begin() as cleanup:
            cleanup.execute(text("DROP TABLE IF EXISTS seed_lock_probe"))
        engine.dispose()

    assert new_id == 6


async def test_application_startup_does_not_seed(
    integration_app: tuple[OIDCOpenAPIFastAPI, LifespanManager],
    integration_engine: AsyncEngine,
) -> None:
    async with integration_engine.connect() as connection:
        count = await connection.scalar(select(func.count()).select_from(Entity))

    assert count == 0
