from collections.abc import Iterator

import pytest
from asgi_lifespan import LifespanManager
from sqlalchemy import Connection, create_engine, delete, func, select, text
from sqlalchemy.ext.asyncio import AsyncEngine

from app.auth import OIDCOpenAPIFastAPI
from app.model import Entity
from seed import seed
from seed.fixtures import FIXTURES

pytestmark = pytest.mark.integration


@pytest.fixture
def connection(test_postgres_url: str) -> Iterator[Connection]:
    engine = create_engine(test_postgres_url)
    try:
        with engine.connect() as connection:
            yield connection
            connection.rollback()
    finally:
        engine.dispose()


def _entity_rows(connection: Connection) -> list[tuple[object, ...]]:
    statement = select(Entity.__table__).order_by(Entity.id)
    return [tuple(row) for row in connection.execute(statement)]


def test_seeding_twice_changes_nothing(connection: Connection) -> None:
    connection.execute(delete(Entity))

    first = seed(connection, FIXTURES)
    rows_after_first = _entity_rows(connection)
    second = seed(connection, FIXTURES)

    assert first == {"entities": len(FIXTURES["entities"])}
    assert second == {"entities": 0}
    assert _entity_rows(connection) == rows_after_first


def test_next_insert_after_explicit_ids_gets_a_new_id(connection: Connection) -> None:
    connection.execute(
        text(
            "CREATE TABLE seed_probe ("
            "id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name text)"
        )
    )

    seed(connection, {"seed_probe": [{"id": 1, "name": "a"}, {"id": 7, "name": "b"}]})
    new_id = connection.scalar(
        text("INSERT INTO seed_probe (name) VALUES ('c') RETURNING id")
    )

    assert new_id == 8


def test_sequence_never_moves_backwards(connection: Connection) -> None:
    connection.execute(
        text(
            "CREATE TABLE seed_probe ("
            "id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name text)"
        )
    )
    connection.execute(
        text("INSERT INTO seed_probe (name) SELECT 'x' FROM generate_series(1, 20)")
    )
    connection.execute(text("DELETE FROM seed_probe WHERE id > 2"))

    seed(connection, {"seed_probe": [{"id": 3, "name": "seeded"}]})
    new_id = connection.scalar(
        text("INSERT INTO seed_probe (name) VALUES ('c') RETURNING id")
    )

    assert new_id == 21


async def test_application_startup_does_not_seed(
    integration_app: tuple[OIDCOpenAPIFastAPI, LifespanManager],
    integration_engine: AsyncEngine,
) -> None:
    async with integration_engine.connect() as connection:
        count = await connection.scalar(select(func.count()).select_from(Entity))

    assert count == 0
