from collections.abc import Mapping, Sequence

from sqlalchemy import (
    Column,
    Connection,
    MetaData,
    Table,
    cast,
    func,
    select,
    table,
    text,
)
from sqlalchemy.dialects.postgresql import REGCLASS, insert

type Row = Mapping[str, object]
type Fixtures = Mapping[str, Sequence[Row]]

_PG_SEQUENCE = table("pg_sequence", Column("seqrelid"), Column("seqincrement"))


def seed(connection: Connection, fixtures: Fixtures) -> dict[str, int]:
    metadata = MetaData()
    metadata.reflect(bind=connection, only=list(fixtures))
    inserted: dict[str, int] = {}
    for seeded_table in metadata.sorted_tables:
        rows = fixtures.get(seeded_table.name)
        if not rows:
            continue
        _reject_always_identity_values(seeded_table, rows)
        _lock_against_writers(connection, seeded_table)
        inserted[seeded_table.name] = sum(
            _insert_row(connection, seeded_table, row) for row in rows
        )
        _advance_sequences(connection, seeded_table)
    return inserted


def _lock_against_writers(connection: Connection, seeded_table: Table) -> None:
    table_name = connection.dialect.identifier_preparer.format_table(seeded_table)
    connection.execute(text(f"LOCK TABLE {table_name} IN SHARE ROW EXCLUSIVE MODE"))


def _reject_always_identity_values(seeded_table: Table, rows: Sequence[Row]) -> None:
    for column in seeded_table.c:
        identity = column.identity
        if identity is None or not identity.always:
            continue
        if any(column.name in row for row in rows):
            msg = (
                f"{seeded_table.name}.{column.name} is GENERATED ALWAYS, so fixtures "
                "cannot set it; use GENERATED BY DEFAULT for seeded IDs"
            )
            raise ValueError(msg)


def _insert_row(connection: Connection, seeded_table: Table, row: Row) -> int:
    statement = (
        insert(seeded_table)
        .values(row)
        .on_conflict_do_nothing()
        .returning(*seeded_table.c)
    )
    return len(connection.execute(statement).all())


def _advance_sequences(connection: Connection, seeded_table: Table) -> None:
    table_name = connection.dialect.identifier_preparer.format_table(seeded_table)
    for column in seeded_table.c:
        sequence = connection.scalar(
            select(func.pg_get_serial_sequence(table_name, column.name))
        )
        if sequence is not None:
            _advance_sequence(connection, seeded_table, column, sequence)


def _advance_sequence(
    connection: Connection,
    seeded_table: Table,
    column: Column[object],
    sequence: str,
) -> None:
    sequence_id = cast(sequence, REGCLASS)
    increment = connection.scalar(
        select(_PG_SEQUENCE.c.seqincrement).where(
            _PG_SEQUENCE.c.seqrelid == sequence_id
        )
    )
    furthest, further = (
        (func.max, func.greatest)
        if increment is None or increment > 0
        else (func.min, func.least)
    )
    stored = select(furthest(column)).select_from(seeded_table).scalar_subquery()
    last_value = func.coalesce(func.pg_sequence_last_value(sequence_id), stored)
    connection.execute(select(func.setval(sequence_id, further(stored, last_value))))
