from collections.abc import Mapping, Sequence
from dataclasses import dataclass
from itertools import groupby

from sqlalchemy import (
    Column,
    Connection,
    MetaData,
    Table,
    UniqueConstraint,
    cast,
    func,
    select,
    table,
    text,
)
from sqlalchemy.dialects.postgresql import REGCLASS, insert

type Row = Mapping[str, object]
type Fixtures = Mapping[str, Sequence[Row]]

_PG_CLASS = table("pg_class", Column("oid"), Column("relname"), Column("relnamespace"))
_PG_NAMESPACE = table("pg_namespace", Column("oid"), Column("nspname"))
_PG_SEQUENCE = table(
    "pg_sequence",
    Column("seqrelid"),
    Column("seqincrement"),
    Column("seqmin"),
    Column("seqmax"),
)


@dataclass(frozen=True)
class _SequencePosition:
    column: Column[object]
    sequence: str
    increment: int
    minimum: int
    maximum: int
    next_value: int


def seed(connection: Connection, fixtures: Fixtures) -> dict[str, int]:
    metadata = MetaData()
    metadata.reflect(bind=connection, only=list(fixtures))
    inserted: dict[str, int] = {}
    for seeded_table in metadata.sorted_tables:
        rows = fixtures.get(seeded_table.name)
        if not rows:
            continue
        _reject_always_identity_values(seeded_table, rows)
        _require_conflict_keys(seeded_table, rows)
        _lock_against_writers(connection, seeded_table)
        before = _sequence_positions(connection, seeded_table)
        inserted[seeded_table.name] = _insert_rows(connection, seeded_table, rows)
        for position in before:
            _restart_past_stored_ids(connection, seeded_table, position)
    return inserted


def _lock_against_writers(connection: Connection, seeded_table: Table) -> None:
    table_name = connection.dialect.identifier_preparer.format_table(seeded_table)
    connection.execute(text(f"LOCK TABLE {table_name} IN SHARE ROW EXCLUSIVE MODE"))


def _reject_always_identity_values(seeded_table: Table, rows: Sequence[Row]) -> None:
    for column in seeded_table.c:
        identity = column.identity
        if identity is None or not identity.always:
            continue
        if any(column.name in row for row in rows):
            msg = (
                f"{seeded_table.name}.{column.name} is GENERATED ALWAYS, so fixtures "
                "cannot set it; use GENERATED BY DEFAULT for seeded IDs"
            )
            raise ValueError(msg)


def _require_conflict_keys(seeded_table: Table, rows: Sequence[Row]) -> None:
    keys = [frozenset(column.name for column in seeded_table.primary_key.columns)]
    keys += [
        frozenset(column.name for column in constraint.columns)
        for constraint in seeded_table.constraints
        if isinstance(constraint, UniqueConstraint)
    ]
    keys += [
        frozenset(column.name for column in index.columns)
        for index in seeded_table.indexes
        if index.unique
        and len(index.columns) == len(index.expressions)
        and index.dialect_options["postgresql"]["where"] is None
    ]
    keys = [key for key in keys if key]
    for row in rows:
        present = {name for name, value in row.items() if value is not None}
        if not any(key <= present for key in keys):
            msg = (
                f"{seeded_table.name} fixture rows must set a primary key or unique "
                "key, otherwise every run inserts them again"
            )
            raise ValueError(msg)


def _insert_rows(
    connection: Connection, seeded_table: Table, rows: Sequence[Row]
) -> int:
    statement = insert(seeded_table).on_conflict_do_nothing().returning(*seeded_table.c)
    return sum(
        len(connection.execute(statement, list(batch)).all())
        for _, batch in groupby(rows, key=frozenset)
    )


def _sequence_positions(
    connection: Connection, seeded_table: Table
) -> list[_SequencePosition]:
    table_name = connection.dialect.identifier_preparer.format_table(seeded_table)
    positions: list[_SequencePosition] = []
    for column in seeded_table.c:
        sequence = connection.scalar(
            select(func.pg_get_serial_sequence(table_name, column.name))
        )
        if sequence is not None:
            positions.append(_sequence_position(connection, column, sequence))
    return positions


def _sequence_position(
    connection: Connection, column: Column[object], sequence: str
) -> _SequencePosition:
    schema, name, increment, minimum, maximum = connection.execute(
        select(
            _PG_NAMESPACE.c.nspname,
            _PG_CLASS.c.relname,
            _PG_SEQUENCE.c.seqincrement,
            _PG_SEQUENCE.c.seqmin,
            _PG_SEQUENCE.c.seqmax,
        )
        .join_from(
            _PG_CLASS, _PG_NAMESPACE, _PG_CLASS.c.relnamespace == _PG_NAMESPACE.c.oid
        )
        .join(_PG_SEQUENCE, _PG_SEQUENCE.c.seqrelid == _PG_CLASS.c.oid)
        .where(_PG_CLASS.c.oid == cast(sequence, REGCLASS))
    ).one()
    state = table(name, Column("last_value"), Column("is_called"), schema=schema)
    last_value, is_called = connection.execute(
        select(state.c.last_value, state.c.is_called)
    ).one()
    next_value = last_value + increment if is_called else last_value
    return _SequencePosition(column, sequence, increment, minimum, maximum, next_value)


def _restart_past_stored_ids(
    connection: Connection, seeded_table: Table, before: _SequencePosition
) -> None:
    furthest = func.max if before.increment > 0 else func.min
    stored = connection.scalar(
        select(furthest(before.column))
        .select_from(seeded_table)
        .where(before.column.between(before.minimum, before.maximum))
    )
    target = before.next_value
    if stored is not None and (stored - target) * before.increment >= 0:
        steps = (stored - target) // before.increment + 1
        advanced = target + steps * before.increment
        if before.minimum <= advanced <= before.maximum:
            target = advanced
    after = _sequence_position(connection, before.column, before.sequence)
    if target != after.next_value:
        connection.execute(
            text(f"ALTER SEQUENCE {before.sequence} RESTART WITH {int(target)}")
        )
