from collections.abc import Mapping, Sequence

from sqlalchemy import (
    Column,
    Connection,
    MetaData,
    Table,
    cast,
    func,
    select,
    table,
    text,
)
from sqlalchemy.dialects.postgresql import REGCLASS, insert

type Row = Mapping[str, object]
type Fixtures = Mapping[str, Sequence[Row]]

_PG_CLASS = table("pg_class", Column("oid"), Column("relname"), Column("relnamespace"))
_PG_NAMESPACE = table("pg_namespace", Column("oid"), Column("nspname"))
_PG_SEQUENCE = table("pg_sequence", Column("seqrelid"), Column("seqincrement"))


def seed(connection: Connection, fixtures: Fixtures) -> dict[str, int]:
    metadata = MetaData()
    metadata.reflect(bind=connection, only=list(fixtures))
    inserted: dict[str, int] = {}
    for seeded_table in metadata.sorted_tables:
        rows = fixtures.get(seeded_table.name)
        if not rows:
            continue
        _reject_always_identity_values(seeded_table, rows)
        _lock_against_writers(connection, seeded_table)
        inserted[seeded_table.name] = _insert_rows(connection, seeded_table, rows)
        _advance_sequences(connection, seeded_table)
    return inserted


def _lock_against_writers(connection: Connection, seeded_table: Table) -> None:
    table_name = connection.dialect.identifier_preparer.format_table(seeded_table)
    connection.execute(text(f"LOCK TABLE {table_name} IN SHARE ROW EXCLUSIVE MODE"))


def _reject_always_identity_values(seeded_table: Table, rows: Sequence[Row]) -> None:
    for column in seeded_table.c:
        identity = column.identity
        if identity is None or not identity.always:
            continue
        if any(column.name in row for row in rows):
            msg = (
                f"{seeded_table.name}.{column.name} is GENERATED ALWAYS, so fixtures "
                "cannot set it; use GENERATED BY DEFAULT for seeded IDs"
            )
            raise ValueError(msg)


def _insert_rows(
    connection: Connection, seeded_table: Table, rows: Sequence[Row]
) -> int:
    batches: dict[frozenset[str], list[Row]] = {}
    for row in rows:
        batches.setdefault(frozenset(row), []).append(row)
    statement = insert(seeded_table).on_conflict_do_nothing().returning(*seeded_table.c)
    return sum(
        len(connection.execute(statement, batch).all()) for batch in batches.values()
    )


def _advance_sequences(connection: Connection, seeded_table: Table) -> None:
    table_name = connection.dialect.identifier_preparer.format_table(seeded_table)
    for column in seeded_table.c:
        sequence = connection.scalar(
            select(func.pg_get_serial_sequence(table_name, column.name))
        )
        if sequence is not None:
            _advance_sequence(connection, seeded_table, column, sequence)


def _advance_sequence(
    connection: Connection,
    seeded_table: Table,
    column: Column[object],
    sequence: str,
) -> None:
    schema, name, increment = connection.execute(
        select(
            _PG_NAMESPACE.c.nspname,
            _PG_CLASS.c.relname,
            _PG_SEQUENCE.c.seqincrement,
        )
        .join_from(
            _PG_CLASS, _PG_NAMESPACE, _PG_CLASS.c.relnamespace == _PG_NAMESPACE.c.oid
        )
        .join(_PG_SEQUENCE, _PG_SEQUENCE.c.seqrelid == _PG_CLASS.c.oid)
        .where(_PG_CLASS.c.oid == cast(sequence, REGCLASS))
    ).one()
    state = table(name, Column("last_value"), Column("is_called"), schema=schema)
    last_value, is_called = connection.execute(
        select(state.c.last_value, state.c.is_called)
    ).one()
    next_value = last_value + increment if is_called else last_value
    furthest = func.max if increment > 0 else func.min
    stored = connection.scalar(select(furthest(column)).select_from(seeded_table))
    if stored is None or (next_value - stored) * increment > 0:
        return
    connection.execute(
        text(f"ALTER SEQUENCE {sequence} RESTART WITH {int(stored + increment)}")
    )
